# Generated by Django 5.0 on 2024-02-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('blogId', models.BigIntegerField()),
                ('text', models.CharField(max_length=500)),
            ],
        ),
    ]
