# Generated by Django 5.0 on 2024-02-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('typeId', models.BigIntegerField()),
                ('targetType', models.CharField(choices=[('blog', 'blog'), ('comment', 'comment')], max_length=8)),
                ('reactionType', models.CharField(choices=[('like', 'like'), ('dislike', 'dislike')], max_length=8)),
            ],
        ),
    ]
